"""Merge bench reports from different engines into one cross-engine comparison.

Feeds on the JSON files written by `bench` and `bench-mlx`. The headline
output is the budget frontier: for each quality budget, the smallest artifact
across every engine that stays inside it.
"""

from __future__ import annotations

import json
from pathlib import Path

from .report import human_size, _tps


def load_report(path: Path) -> dict:
    return json.loads(Path(path).read_text())


def _short_engine(engine: str) -> str:
    if engine.startswith("mlx"):
        return "MLX"
    if engine.startswith("llama.cpp"):
        return "GGUF"
    return engine


def _rows(reports: list[dict]) -> list[dict]:
    rows = []
    for report in reports:
        engine_raw = report.get("engine")
        if not engine_raw:  # reports written before the engine field existed
            engine_raw = "llama.cpp" if str(report.get("source", "")).endswith(".gguf") else "?"
        engine = _short_engine(engine_raw)
        base_size = report["variants"][0]["size_bytes"]  # to_json puts the baseline first
        for v in report["variants"]:
            rows.append(
                {
                    "engine": engine,
                    "name": v["name"],
                    "size_bytes": v["size_bytes"],
                    "dsize_pct": (v["size_bytes"] / base_size - 1) * 100,
                    "ppl": v["ppl"],
                    "dppl_pct": v["ppl_increase_pct"],
                    "generate_tps": v.get("generate_tps"),
                }
            )
    rows.sort(key=lambda r: -r["size_bytes"])
    return rows


def render_comparison(
    reports: list[dict], budgets: tuple[float, ...] = (0.5, 1.0, 2.0, 5.0)
) -> str:
    rows = _rows(reports)
    names = sorted({Path(r["source"]).name for r in reports})
    hardware = reports[0].get("hardware", {})
    hw_bits = [hardware.get("chip") or hardware.get("machine"), hardware.get("os")]
    if hardware.get("memory_gb"):
        hw_bits.insert(1, f"{hardware['memory_gb']} GB unified memory")

    lines = [
        f"# quantpilot cross-engine comparison: {', '.join(names)}",
        "",
        f"Hardware: {', '.join(str(b) for b in hw_bits if b)}",
        "Δ columns are relative to each engine's own full-precision baseline.",
        "",
        "| Engine | Variant | Size | Δ size | Perplexity | Δ PPL | Gen t/s |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['engine']} | {r['name']} | {human_size(r['size_bytes'])} "
            f"| {r['dsize_pct']:+.0f}% | {r['ppl']:.4f} | {r['dppl_pct']:+.2f}% "
            f"| {_tps(r['generate_tps'])} |"
        )

    lines += ["", "## Budget frontier", "", "Smallest artifact within each quality budget, across all engines:", ""]
    for budget in budgets:
        within = [r for r in rows if r["dppl_pct"] <= budget]
        if not within:
            lines.append(f"- ≤ +{budget:g}% PPL: none qualify")
            continue
        best = min(within, key=lambda r: r["size_bytes"])
        lines.append(
            f"- ≤ +{budget:g}% PPL: **{best['engine']} {best['name']}** — "
            f"{human_size(best['size_bytes'])} at {best['dppl_pct']:+.2f}% PPL"
        )

    lines += [
        "",
        "---",
        "*Generated by [quantpilot](https://github.com/collins3355-bot/quantpilot) — quantization autotuning for local models.*",
    ]
    return "\n".join(lines) + "\n"
