"""`quantpilot fit` — which measured artifact actually fits your machine?

Feeds on a bench report JSON (GGUF engine) and re-ranks its variants by
runtime footprint at a target context length against a memory budget.
The recommendation is the highest-quality variant that fits.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .memory import KV_BYTES, ModelShape, footprint, kv_bytes_per_token, shape_of
from .report import human_size


class FitError(RuntimeError):
    pass


@dataclass
class FitRow:
    name: str
    weights_bytes: int
    kv_bytes: int
    total_bytes: int
    dppl_pct: float
    fits: bool


def load_report(path: Path) -> dict:
    report = json.loads(path.read_text())
    engine = report.get("engine", "")
    if not engine.startswith("llama.cpp"):
        raise FitError(
            "fit currently supports GGUF (llama.cpp) reports — the MLX side "
            "needs HF config parsing, which is on the roadmap"
        )
    return report


def find_shape(report: dict) -> ModelShape:
    """Read architecture shape from any of the report's artifacts still on disk."""
    for v in report["variants"]:
        path = Path(v["path"])
        if path.is_file():
            return shape_of(path)
    raise FitError(
        "none of the report's artifacts exist on disk to read GGUF metadata "
        "from — re-run bench, or keep at least one .gguf around"
    )


def compute_rows(
    report: dict, shape: ModelShape, ctx: int, kv_type: str, budget_bytes: float
) -> list[FitRow]:
    rows = []
    for v in report["variants"]:
        fp = footprint(v["size_bytes"], shape, ctx, kv_type)
        rows.append(
            FitRow(
                name=v["name"],
                weights_bytes=fp.weights_bytes,
                kv_bytes=fp.kv_bytes,
                total_bytes=fp.total_bytes,
                dppl_pct=v["ppl_increase_pct"],
                fits=fp.total_bytes <= budget_bytes,
            )
        )
    return rows


def recommend(rows: list[FitRow]) -> FitRow | None:
    fitting = [r for r in rows if r.fits]
    return min(fitting, key=lambda r: r.dppl_pct) if fitting else None


def render(
    report: dict,
    rows: list[FitRow],
    shape: ModelShape,
    ctx: int,
    kv_type: str,
    ram_gb: float,
    headroom: float,
    hardware: dict,
) -> str:
    budget_gb = ram_gb * headroom
    source = Path(report["source"]).name
    hw_bits = [hardware.get("chip") or hardware.get("machine")]
    lines = [
        f"# quantpilot fit report: {source}",
        "",
        f"Machine: {', '.join(str(b) for b in hw_bits if b)}, {ram_gb:g} GB RAM "
        f"→ {budget_gb:.1f} GB usable (headroom ×{headroom:g})",
        f"Target: {ctx:,} tokens of context, {kv_type} KV cache "
        f"({kv_bytes_per_token(shape, kv_type) / 1024:.0f} KB/token on {shape.arch}, "
        f"{shape.block_count} layers × {shape.head_count_kv} KV heads)",
        "",
        "| Variant | Weights | KV cache | Est. total | Fits? | Δ PPL |",
        "|---|---|---|---|---|---|",
    ]
    if shape.context_length and ctx > shape.context_length:
        lines.insert(
            4,
            f"⚠️ requested context exceeds the model's declared maximum "
            f"({shape.context_length:,}).",
        )
    for r in rows:
        mark = "✅" if r.fits else "✗"
        lines.append(
            f"| {r.name} | {human_size(r.weights_bytes)} | {human_size(r.kv_bytes)} "
            f"| {human_size(r.total_bytes)} | {mark} | {r.dppl_pct:+.2f}% |"
        )
    best = recommend(rows)
    lines += ["", "## Recommendation", ""]
    if best is None:
        lines.append(
            f"**Nothing fits** in {budget_gb:.1f} GB at {ctx:,} context — try a "
            f"smaller quant, a shorter context, a quantized KV cache "
            f"(`--kv-type q8_0`), or a smaller model."
        )
    else:
        lines.append(
            f"**{best.name}** — {human_size(best.total_bytes)} total at {ctx:,} "
            f"context ({best.dppl_pct:+.2f}% PPL), the highest-quality variant "
            f"inside {budget_gb:.1f} GB."
        )
    lines += [
        "",
        "Estimates cover weights + KV cache; compute buffers and OS overhead are "
        "extra — that's what the headroom is for.",
        "",
        "---",
        "*Generated by [quantpilot](https://github.com/collins3355-bot/quantpilot) — quantization autotuning for local models.*",
    ]
    return "\n".join(lines) + "\n"
