"""Turn a BenchRun into a human-readable markdown report and a machine-readable JSON."""

from __future__ import annotations

import json

from .pipeline import BenchRun, Variant


def human_size(size_bytes: int) -> str:
    if size_bytes >= 1024**3:
        return f"{size_bytes / 1024**3:.2f} GB"
    return f"{size_bytes / 1024**2:.0f} MB"


def _tps(value: float | None) -> str:
    return f"{value:,.0f}" if value is not None else "—"


def _row(v: Variant, baseline: Variant) -> str:
    delta_ppl = v.ppl_increase_pct(baseline.ppl)
    delta_size = (v.size_bytes / baseline.size_bytes - 1) * 100
    return (
        f"| {v.name} | {human_size(v.size_bytes)} | {delta_size:+.0f}% "
        f"| {v.ppl:.4f} | {delta_ppl:+.2f}% | {_tps(v.prompt_tps)} | {_tps(v.generate_tps)} |"
    )


def render_markdown(run: BenchRun, hardware: dict) -> str:
    rec = run.recommendation()
    hw_bits = [hardware.get("chip") or hardware.get("machine"), hardware.get("os")]
    if hardware.get("memory_gb"):
        hw_bits.insert(1, f"{hardware['memory_gb']} GB unified memory")
    lines = [
        f"# quantpilot report: {run.source.name}",
        "",
        f"Hardware: {', '.join(str(b) for b in hw_bits if b)}",
        f"Quality metric: perplexity over {run.chunks} × 512-token chunks of `{run.corpus.name}`",
        f"Quality budget: ≤ {run.budget_pct:g}% perplexity increase vs. baseline",
        "",
        "| Variant | Size | Δ size | Perplexity | Δ PPL | Prompt t/s | Gen t/s |",
        "|---|---|---|---|---|---|---|",
    ]
    lines += [_row(v, run.baseline) for v in run.all_variants()]
    saved = (1 - rec.size_bytes / run.baseline.size_bytes) * 100
    lines += [
        "",
        "## Recommendation",
        "",
        f"**{rec.name}** — {human_size(rec.size_bytes)} "
        f"({saved:.0f}% smaller than baseline) at "
        f"{rec.ppl_increase_pct(run.baseline.ppl):+.2f}% perplexity, "
        f"inside the {run.budget_pct:g}% budget.",
        "",
        f"Artifact: `{rec.path}`",
        "",
        "---",
        "*Generated by [quantpilot](https://github.com/) — quantization autotuning for local models.*",
    ]
    return "\n".join(lines) + "\n"


def to_json(run: BenchRun, hardware: dict) -> str:
    rec = run.recommendation()
    payload = {
        "source": str(run.source),
        "corpus": str(run.corpus),
        "chunks": run.chunks,
        "budget_pct": run.budget_pct,
        "hardware": hardware,
        "variants": [
            {
                "name": v.name,
                "path": str(v.path),
                "size_bytes": v.size_bytes,
                "ppl": v.ppl,
                "ppl_err": v.ppl_err,
                "ppl_increase_pct": v.ppl_increase_pct(run.baseline.ppl),
                "prompt_tps": v.prompt_tps,
                "generate_tps": v.generate_tps,
            }
            for v in run.all_variants()
        ],
        "recommendation": rec.name,
    }
    return json.dumps(payload, indent=2) + "\n"
