"""Turn a BenchRun into a human-readable markdown report and a machine-readable JSON."""

from __future__ import annotations

import json

from .pipeline import BenchRun, Variant
from .search import SearchResult


def _hardware_line(hardware: dict) -> str:
    bits = [hardware.get("chip") or hardware.get("machine"), hardware.get("os")]
    if hardware.get("memory_gb"):
        bits.insert(1, f"{hardware['memory_gb']} GB unified memory")
    return ", ".join(str(b) for b in bits if b)


def human_size(size_bytes: int) -> str:
    if size_bytes >= 1024**3:
        return f"{size_bytes / 1024**3:.2f} GB"
    return f"{size_bytes / 1024**2:.0f} MB"


def _tps(value: float | None) -> str:
    return f"{value:,.0f}" if value is not None else "—"


def _row(v: Variant, baseline: Variant, kld: bool) -> str:
    delta_ppl = v.ppl_increase_pct(baseline.ppl)
    delta_size = (v.size_bytes / baseline.size_bytes - 1) * 100
    cells = [
        v.name,
        human_size(v.size_bytes),
        f"{delta_size:+.0f}%",
        f"{v.ppl:.4f}",
        f"{delta_ppl:+.2f}%",
    ]
    if kld:
        cells.append(f"{v.mean_kld:.4f}" if v.mean_kld is not None else "—")
        cells.append(f"{v.same_top_pct:.1f}%" if v.same_top_pct is not None else "—")
    cells += [_tps(v.prompt_tps), _tps(v.generate_tps)]
    return "| " + " | ".join(cells) + " |"


def render_markdown(run: BenchRun, hardware: dict) -> str:
    rec = run.recommendation()
    hw_bits = [hardware.get("chip") or hardware.get("machine"), hardware.get("os")]
    if hardware.get("memory_gb"):
        hw_bits.insert(1, f"{hardware['memory_gb']} GB unified memory")
    kld = run.baseline.mean_kld is not None
    metric = f"perplexity over {run.chunks} × 512-token chunks of `{run.corpus.name}`"
    if kld:
        metric += ", plus KL divergence of each quant's token distributions vs. baseline"
    header = ["Variant", "Size", "Δ size", "Perplexity", "Δ PPL"]
    if kld:
        header += ["Mean KLD", "Top-1 agree"]
    header += ["Prompt t/s", "Gen t/s"]
    lines = [
        f"# quantpilot report: {run.source.name}",
        "",
        f"Hardware: {', '.join(str(b) for b in hw_bits if b)}",
        f"Engine: {run.engine}",
        f"Quality metric: {metric}",
        f"Quality budget: ≤ {run.budget_pct:g}% perplexity increase vs. baseline",
        "",
        "| " + " | ".join(header) + " |",
        "|" + "---|" * len(header),
    ]
    lines += [_row(v, run.baseline, kld) for v in run.all_variants()]
    saved = (1 - rec.size_bytes / run.baseline.size_bytes) * 100
    lines += [
        "",
        "## Recommendation",
        "",
        f"**{rec.name}** — {human_size(rec.size_bytes)} "
        f"({saved:.0f}% smaller than baseline) at "
        f"{rec.ppl_increase_pct(run.baseline.ppl):+.2f}% perplexity, "
        f"inside the {run.budget_pct:g}% budget.",
        "",
        f"Artifact: `{rec.path}`",
        "",
        "---",
        "*Generated by [quantpilot](https://github.com/collins3355-bot/quantpilot) — quantization autotuning for local models.*",
    ]
    return "\n".join(lines) + "\n"


def render_search(result: SearchResult, hardware: dict, ladder: dict | None = None) -> str:
    base_dppl = (result.base_ppl - result.baseline_ppl) / result.baseline_ppl * 100
    lines = [
        f"# quantpilot search report: {result.source.name}",
        "",
        f"Hardware: {_hardware_line(hardware)}",
        f"Recipe space: base {result.base}, bump {result.bump}, per tensor class",
        f"Quality metric: perplexity over {result.chunks} × 512-token chunks of `{result.corpus.name}`",
        f"Quality budget: ≤ {result.budget_pct:g}% PPL increase vs. full-precision baseline "
        f"(PPL {result.baseline_ppl:.4f})",
        "",
        f"Uniform {result.base}: {human_size(result.base_size)}, "
        f"PPL {result.base_ppl:.4f} ({base_dppl:+.2f}% vs. baseline)",
        "",
        "## Sensitivity probes (ranked by quality recovered per GB)",
        "",
        "| Class | Size added | PPL | PPL recovered | Recovery / GB |",
        "|---|---|---|---|---|",
    ]
    for p in result.probes:
        lines.append(
            f"| {p.cls} | +{p.size_delta / 1024**2:.0f} MB | {p.ppl:.4f} "
            f"| {p.ppl_recovered:+.4f} | {p.recovery_per_gb:.3f} |"
        )

    if result.failed:
        lines += [
            "",
            f"Probes skipped (crashed — likely tensor shapes incompatible with "
            f"{result.bump}): {', '.join(result.failed)}",
        ]

    lines += ["", "## Composition", "", "| Step | Recipe | Size | Δ PPL vs. baseline |", "|---|---|---|---|"]
    for i, s in enumerate(result.steps, start=1):
        recipe = f"{result.base} + {{{', '.join(s.classes)}}}→{result.bump}"
        mark = " ✅" if s.dppl_pct <= result.budget_pct else ""
        lines.append(
            f"| {i} | {recipe} | {human_size(s.size_bytes)} | {s.dppl_pct:+.2f}%{mark} |"
        )

    lines += ["", "## Result", ""]
    if result.met_budget and result.steps:
        final = result.steps[-1]
        lines.append(
            f"**Met the {result.budget_pct:g}% budget** at {human_size(final.size_bytes)} "
            f"({final.dppl_pct:+.2f}% PPL) with {len(final.classes)} class bump(s): "
            f"{', '.join(final.classes)}."
        )
    else:
        lines.append(
            f"**Did not meet the {result.budget_pct:g}% budget** within this recipe space — "
            f"consider a higher base type or a larger bump."
        )
    if ladder:
        within = [
            v
            for v in ladder["variants"][1:]
            if v["ppl_increase_pct"] <= result.budget_pct
        ]
        if within and result.met_budget and result.steps:
            best_uniform = min(within, key=lambda v: v["size_bytes"])
            saved = best_uniform["size_bytes"] - result.steps[-1].size_bytes
            lines += [
                "",
                f"Uniform ladder comparison: the smallest preset inside the budget was "
                f"**{best_uniform['name']}** at {human_size(best_uniform['size_bytes'])} "
                f"({best_uniform['ppl_increase_pct']:+.2f}%). The composed recipe is "
                f"{human_size(abs(saved))} {'smaller' if saved > 0 else 'larger'}.",
            ]
    if result.final_path is not None:
        lines += ["", f"Artifact: `{result.final_path}`"]
    if result.recipe_command():
        lines += ["", "Reproduce:", "", "```", result.recipe_command(), "```"]
    lines += [
        "",
        "---",
        "*Generated by [quantpilot](https://github.com/collins3355-bot/quantpilot) — quantization autotuning for local models.*",
    ]
    return "\n".join(lines) + "\n"


def search_to_json(result: SearchResult, hardware: dict) -> str:
    payload = {
        "source": str(result.source),
        "engine": "llama.cpp",
        "base": result.base,
        "bump": result.bump,
        "budget_pct": result.budget_pct,
        "chunks": result.chunks,
        "corpus": str(result.corpus),
        "hardware": hardware,
        "baseline_ppl": result.baseline_ppl,
        "base_ppl": result.base_ppl,
        "base_size_bytes": result.base_size,
        "probes": [
            {
                "class": p.cls,
                "size_delta_bytes": p.size_delta,
                "ppl": p.ppl,
                "ppl_recovered": p.ppl_recovered,
                "recovery_per_gb": p.recovery_per_gb,
            }
            for p in result.probes
        ],
        "steps": [
            {
                "classes": s.classes,
                "size_bytes": s.size_bytes,
                "ppl": s.ppl,
                "dppl_pct": s.dppl_pct,
            }
            for s in result.steps
        ],
        "met_budget": result.met_budget,
        "failed_probes": result.failed,
        "final_path": str(result.final_path) if result.final_path else None,
        "recipe_command": result.recipe_command(),
    }
    return json.dumps(payload, indent=2) + "\n"


def to_json(run: BenchRun, hardware: dict) -> str:
    rec = run.recommendation()
    payload = {
        "source": str(run.source),
        "engine": run.engine,
        "corpus": str(run.corpus),
        "chunks": run.chunks,
        "budget_pct": run.budget_pct,
        "hardware": hardware,
        "variants": [
            {
                "name": v.name,
                "path": str(v.path),
                "size_bytes": v.size_bytes,
                "ppl": v.ppl,
                "ppl_err": v.ppl_err,
                "ppl_increase_pct": v.ppl_increase_pct(run.baseline.ppl),
                "mean_kld": v.mean_kld,
                "same_top_pct": v.same_top_pct,
                "prompt_tps": v.prompt_tps,
                "generate_tps": v.generate_tps,
            }
            for v in run.all_variants()
        ],
        "recommendation": rec.name,
    }
    return json.dumps(payload, indent=2) + "\n"
